DROP TABLE DESCONTOS;
DROP TABLE FUNCIONARIO;

CREATE TABLE FUNCIONARIO (
  ID_CLIENTE NUMBER(8) PRIMARY KEY,
  NM_CLIENTE VARCHAR (30),
  VL_SALARIO_BRUTO NUMBER(10, 2)
);

CREATE TABLE DESCONTOS (
  ID_DESCONTO NUMBER(3) PRIMARY KEY,
  ID_CLIENTE NUMBER(8),
  VL_DESCONTO NUMBER(5, 2)
);

INSERT INTO FUNCIONARIO (ID_CLIENTE, NM_CLIENTE, VL_SALARIO_BRUTO) VALUES (1, 'FERNANDO TEIXEIRA', 1111.11);
INSERT INTO DESCONTOS (ID_DESCONTO, ID_CLIENTE, VL_DESCONTO) VALUES (1, 1, 22.22);
INSERT INTO DESCONTOS (ID_DESCONTO, ID_CLIENTE, VL_DESCONTO) VALUES (2, 1, 33.33);
